using System.Text.RegularExpressions;
namespace Core;

public sealed record FeatureRequest(string Title,string Description,string Audience,string Constraints);
public sealed record FeaturePlan(string Title,string Markdown);
public interface IRequirementsGenerator { FeaturePlan Generate(FeatureRequest request); }
public interface IIssuePublisher { Task<Uri> PublishAsync(string repository,FeaturePlan plan,CancellationToken cancellationToken); }

// A deterministic free provider. A future server-side AI adapter can implement the same interface.
public sealed class TemplateRequirementsGenerator : IRequirementsGenerator
{
    public FeaturePlan Generate(FeatureRequest request)
    {
        if (string.IsNullOrWhiteSpace(request.Title) || request.Title.Length>120) throw new ArgumentException("Use a title between 1 and 120 characters.");
        if (string.IsNullOrWhiteSpace(request.Description) || request.Description.Length>2000) throw new ArgumentException("Describe the feature in 1–2,000 characters.");
        if (request.Audience.Length>200 || request.Constraints.Length>1000) throw new ArgumentException("Audience or constraints are too long.");
        var text=request.Description.ToLowerInvariant();
        var requirements=new List<string>{"Provide a discoverable entry point with clear labels and keyboard access.","Show useful empty, loading, success and error states.","Preserve existing behavior and existing user data."};
        if(text.Contains("csv") || text.Contains("export")) requirements.AddRange(["Export the selected dataset with a header row and UTF-8 encoding.","Escape separators, quotes and newlines; neutralize spreadsheet formula injection.","Honor the current filters and document the exported columns."]);
        if(text.Contains("login") || text.Contains("auth")) requirements.AddRange(["Use an established identity provider; never store plaintext passwords.","Enforce authorization at the server for every protected resource.","Support sign-out, expired-session handling and accessible sign-in errors."]);
        if(text.Contains("notification") || text.Contains("remind")) requirements.AddRange(["Ask for notification permission only after an explicit user action.","Store the intended timezone and handle daylight-saving changes.","Prevent duplicate sends and provide an opt-out."]);
        if(text.Contains("search") || text.Contains("filter")) requirements.AddRange(["Define searchable fields and case sensitivity.","Provide a clear-filters action and a no-results state."]);
        string bullets(IEnumerable<string> values)=>string.Join("\n",values.Select(x=>"- "+x));
        var markdown=$"## Goal\n{request.Description.Trim()}\n\n## User story\nAs {request.Audience.Trim()}, I want {request.Title.Trim().TrimEnd('.')}, so that the requested workflow is easier to complete.\n\n## Requirements to review\n{bullets(requirements)}\n\n## Acceptance criteria\n- [ ] Given valid input, when the primary action is used, the stated result is produced.\n- [ ] Given missing or invalid input, show an actionable error without losing user input.\n- [ ] Given a small screen or keyboard-only input, the workflow remains usable.\n- [ ] Add feature-specific examples and expected outputs before implementation.\n\n## Implementation tasks\n- [ ] Confirm scope and data ownership.\n- [ ] Implement domain behavior and meaningful tests.\n- [ ] Build the UI and integration adapter where needed.\n- [ ] Verify mobile layout and update the README.\n\n## Constraints\n{(string.IsNullOrWhiteSpace(request.Constraints)?"No constraints supplied; confirm before implementation.":request.Constraints.Trim())}\n\n## Test plan\n- Happy path with realistic sample input.\n- Empty input, invalid input and boundary values.\n- Regression, keyboard navigation and mobile viewport.\n\n## Open questions\n- What exact result defines success?\n- Which fields, roles and edge cases are in scope?\n- Are there privacy, cost or compatibility constraints?\n\n_Generated by the free template planner. This is a draft, not an AI analysis; review and refine before implementation._";
        return new(request.Title.Trim(),markdown);
    }
}
public static partial class GitHubDraft
{
    [GeneratedRegex(@"^[A-Za-z0-9-]+/[A-Za-z0-9_.-]+$")]
    private static partial Regex RepositoryPattern();
    public static Uri Url(string repository,FeaturePlan plan)
    {
        if (!RepositoryPattern().IsMatch(repository)) throw new ArgumentException("Use a GitHub repository in owner/name format.");
        // Limit URL size for mobile browser compatibility. Longer drafts should be pasted from Markdown.
        var body=plan.Markdown.Length>4500 ? plan.Markdown[..4500]+"\n\n[Draft truncated: paste the complete downloaded Markdown before submitting.]" : plan.Markdown;
        return new Uri($"https://github.com/{repository}/issues/new?title={Uri.EscapeDataString(plan.Title)}&body={Uri.EscapeDataString(body)}");
    }
}
